import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Elixir Cósmico',
    description: 'Uma bebida brilhante e doce que tem gosto de galáxia.',
    price: 12.50,
    image: 'https://placehold.co/600x600.png',
    tags: ['Novo'],
    dataAiHint: 'cocktail vibrant',
  },
  {
    id: '2',
    name: 'Brisa do Oceano',
    description: 'Refrescante, com toque de sal marinho e cítricos.',
    price: 9.00,
    image: 'https://placehold.co/600x600.png',
    tags: ['Mais Vendido'],
    dataAiHint: 'blue drink',
  },
  {
    id: '3',
    name: 'Brilho do Pôr do Sol',
    description: 'Um mocktail quente e condimentado que imita um pôr do sol perfeito.',
    price: 11.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'orange cocktail',
  },
  {
    id: '4',
    name: 'Orvalho da Floresta',
    description: 'Uma mistura terrosa de ervas e botânicos. Pura natureza.',
    price: 10.50,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'green mocktail',
  },
    {
    id: '5',
    name: 'Corrida Rubi',
    description: 'Uma fusão vibrante de frutas vermelhas, azeda e doce.',
    price: 13.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'red drink',
  },
  {
    id: '6',
    name: 'Néctar Dourado',
    description: 'Uma bebida com mel e final suave e rico.',
    price: 14.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'yellow cocktail',
  },
  {
    id: '7',
    name: 'Veludo da Meia-Noite',
    description: 'Uma bebida escura e misteriosa com notas de café e chocolate.',
    price: 15.50,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'dark cocktail',
  },
  {
    id: '8',
    name: 'Beijo Ártico',
    description: 'Uma mistura crocante e mentolada, refrescante como gelo.',
    price: 9.50,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'clear drink',
  },
];
